# Generated by Django 4.0.4 on 2022-05-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.IntegerField(default=0, max_length=10)),
                ('orderDate', models.CharField(default='', max_length=10)),
                ('deliveryDate', models.CharField(default='', max_length=10)),
                ('orderStatus', models.CharField(default='', max_length=15)),
                ('noOfItems', models.IntegerField(default=0, max_length=10)),
            ],
        ),
    ]
