# Generated by Django 4.0.4 on 2022-05-26 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_proddatabase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prodDatabase',
        ),
    ]
