# Generated by Django 3.2.10 on 2022-07-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_proddatabase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('contact', models.CharField(default='', max_length=10)),
                ('address', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
