# Generated by Django 3.2.10 on 2022-05-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(max_length=240)),
                ('prodDescription', models.CharField(max_length=1024)),
                ('prodPrice', models.CharField(max_length=20)),
                ('prodBatch', models.CharField(max_length=20)),
                ('expiryDate', models.CharField(max_length=20)),
                ('isAvailable', models.BooleanField(default=True)),
                ('isPrescriptionRequired', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='prodDatabase',
        ),
    ]
