apiVersion: v1
kind: Service
metadata:
  name: transactions-service
spec:
  selector:
    app: transactions
  ports:
  - protocol: "TCP"
    port: 7002
    targetPort: 8802
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions
spec:
  selector:
    matchLabels:
      app: transactions
  replicas: 4
  template:
    metadata:
      labels:
        app: transactions
    spec:
      containers:
      - name: transactions
        image: transactions:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8802
