apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product
  ports:
  - protocol: "TCP"
    port: 7001
    targetPort: 8801
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  selector:
    matchLabels:
      app: product
  replicas: 4
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: product:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8801
