apiVersion: v1
kind: Service
metadata:
  name: hospitals-service
spec:
  selector:
    app: hospitals
  ports:
  - protocol: "TCP"
    port: 7003
    targetPort: 8803
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospitals
spec:
  selector:
    matchLabels:
      app: hospitals
  replicas: 4
  template:
    metadata:
      labels:
        app: hospitals
    spec:
      containers:
      - name: hospitals
        image: hospitals:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8803
